name: Netflix Movie Catalog Service Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: 44.199.228.19  # Replace with your EC2 instance public IP
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Define this secret in your GitHub repo settings

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          printf "%s" "$SSH_PRIVATE_KEY" > mykey.pem
          chmod 600 mykey.pem

      - name: Create app directory on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@$EC2_PUBLIC_IP "mkdir -p ~/app"

      - name: Copy project files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i mykey.pem \
            app.py data requirements.txt deploy.sh \
            ubuntu@$EC2_PUBLIC_IP:~/app

      - name: Run deploy script on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@$EC2_PUBLIC_IP "bash ~/app/deploy.sh"
